spring:
  application:
    name:
      otus-online-library

  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver

server:
  port: 8189

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            TRACE

